# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Cache to speed up the build
cache: pip

# Set the python versions
python:
- 3.9

# Addons
addons:
  postgresql: '9.6'

# Environment
env:
- DATABASE_URL=postgres://postgres:postgres@localhost:5432/travis_ci_test

# Install pip dependencies
install:
- pip install -r requirements.txt

# Create test database
before_script:
- psql -c 'create database travis_ci_test;' -U postgres

# Run the unit test
script:
- python manage.py test

# Deploy to heroku server
deploy:
  provider: heroku
  api_key:
    secure: SECURE_KEY
  app: event-charge
  on:
    repo: marfyl/travis-heroku
    branch: master